/**
 * Supabase Schema Contract
 * 
 * Authoritative definition of table schemas used by LAIPath.
 * All Supabase insert/select operations MUST use these constants.
 * 
 * This ensures strict alignment between frontend code and database schema.
 */

/**
 * syllabi table columns
 * 
 * Schema (EXACT match with Supabase - DO NOT MODIFY without updating database):
 * - id (uuid)
 * - user_id (uuid, required)
 * - goal (text)
 * - hours_per_day (integer)
 * - total_days (integer)
 * - start_date (date)
 * - created_at (timestamptz)
 * - updated_at (timestamptz)
 * 
 * WARNING: This schema contract MUST match Supabase exactly.
 * Any changes here must be reflected in the database schema.
 */
export const SYLLABI_COLUMNS = {
  // Primary key (generated by Supabase, never included in inserts)
  ID: 'id',
  
  // Foreign key
  USER_ID: 'user_id',
  
  // Content fields
  GOAL: 'goal',
  HOURS_PER_DAY: 'hours_per_day',
  TOTAL_DAYS: 'total_days',
  START_DATE: 'start_date',
  
  // Timestamps (managed by database)
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
}

/**
 * Columns that can be inserted (excludes auto-generated fields)
 */
export const SYLLABI_INSERT_COLUMNS = [
  SYLLABI_COLUMNS.USER_ID,
  SYLLABI_COLUMNS.GOAL,
  SYLLABI_COLUMNS.HOURS_PER_DAY,
  SYLLABI_COLUMNS.TOTAL_DAYS,
  SYLLABI_COLUMNS.START_DATE,
]

/**
 * Columns typically selected for syllabus metadata
 */
export const SYLLABI_SELECT_COLUMNS = [
  SYLLABI_COLUMNS.ID,
  SYLLABI_COLUMNS.GOAL,
  SYLLABI_COLUMNS.HOURS_PER_DAY,
  SYLLABI_COLUMNS.TOTAL_DAYS,
  SYLLABI_COLUMNS.START_DATE,
  SYLLABI_COLUMNS.CREATED_AT,
]

/**
 * syllabus_days table columns
 * 
 * Schema (EXACT match with Supabase - DO NOT MODIFY without updating database):
 * - id (uuid)
 * - syllabus_id (uuid)
 * - day_number (integer)
 * - date (date)
 * - topic (text)
 * - subtasks (jsonb)
 * - ai_expert_prompt (text)
 * - status (text)
 * - learning_input (text, nullable)
 * - completed_at (timestamptz, nullable)
 * - created_at (timestamptz)
 * 
 * WARNING: This schema contract MUST match Supabase exactly.
 * Any changes here must be reflected in the database schema.
 */
export const SYLLABUS_DAYS_COLUMNS = {
  // Primary key (generated by Supabase, never included in inserts)
  ID: 'id',
  
  // Foreign key
  SYLLABUS_ID: 'syllabus_id',
  
  // Content fields
  DAY_NUMBER: 'day_number',
  DATE: 'date',
  TOPIC: 'topic',
  SUBTASKS: 'subtasks',
  AI_EXPERT_PROMPT: 'ai_expert_prompt',
  STATUS: 'status',
  
  // Optional fields
  LEARNING_INPUT: 'learning_input',
  COMPLETED_AT: 'completed_at',
  
  // Timestamp (managed by database)
  CREATED_AT: 'created_at',
}

/**
 * Columns that can be inserted (excludes auto-generated id)
 */
export const SYLLABUS_DAYS_INSERT_COLUMNS = [
  SYLLABUS_DAYS_COLUMNS.SYLLABUS_ID,
  SYLLABUS_DAYS_COLUMNS.DAY_NUMBER,
  SYLLABUS_DAYS_COLUMNS.DATE,
  SYLLABUS_DAYS_COLUMNS.TOPIC,
  SYLLABUS_DAYS_COLUMNS.SUBTASKS,
  SYLLABUS_DAYS_COLUMNS.AI_EXPERT_PROMPT,
  SYLLABUS_DAYS_COLUMNS.STATUS,
  SYLLABUS_DAYS_COLUMNS.LEARNING_INPUT,
  SYLLABUS_DAYS_COLUMNS.COMPLETED_AT,
]

/**
 * Columns typically selected for syllabus days
 */
export const SYLLABUS_DAYS_SELECT_COLUMNS = [
  SYLLABUS_DAYS_COLUMNS.DAY_NUMBER,
  SYLLABUS_DAYS_COLUMNS.DATE,
  SYLLABUS_DAYS_COLUMNS.TOPIC,
  SYLLABUS_DAYS_COLUMNS.SUBTASKS,
  SYLLABUS_DAYS_COLUMNS.AI_EXPERT_PROMPT,
  SYLLABUS_DAYS_COLUMNS.STATUS,
  SYLLABUS_DAYS_COLUMNS.LEARNING_INPUT,
  SYLLABUS_DAYS_COLUMNS.COMPLETED_AT,
  // Note: created_at is available but typically not needed for frontend display
]

/**
 * Strict validation: Ensure payload EXACTLY matches schema contract
 * 
 * This prevents schema drift by enforcing that:
 * - Only allowed columns are present
 * - No unknown fields can be inserted
 * - Column names match exactly
 * 
 * @param {Object} payload - The data payload to validate
 * @param {string[]} allowedColumns - Array of allowed column names from schema
 * @param {string} tableName - Name of the table (for error messages)
 * @returns {Object} - Validation result with isValid and errors
 */
export function validatePayload(payload, allowedColumns, tableName) {
  if (!payload || typeof payload !== 'object') {
    return {
      isValid: false,
      errors: [`Payload must be an object for ${tableName}`],
    }
  }

  const payloadKeys = Object.keys(payload)
  
  // STRICT: Find any keys that are NOT in the allowed columns list
  const invalidKeys = payloadKeys.filter(key => !allowedColumns.includes(key))
  
  // Define nullable/optional columns (these can be undefined/null)
  const optionalColumns = [
    SYLLABUS_DAYS_COLUMNS.LEARNING_INPUT,
    SYLLABUS_DAYS_COLUMNS.COMPLETED_AT,
  ]
  
  // Check for missing required columns (non-optional columns that are undefined)
  const missingRequired = allowedColumns.filter(col => 
    payload[col] === undefined && !optionalColumns.includes(col)
  )

  const errors = []
  
  // CRITICAL: Reject any unknown columns to prevent drift
  if (invalidKeys.length > 0) {
    errors.push(
      `❌ SCHEMA MISMATCH: Invalid columns detected in ${tableName}: ${invalidKeys.join(', ')}. ` +
      `Allowed columns: ${allowedColumns.join(', ')}. ` +
      `This indicates schema drift - fix immediately!`
    )
  }
  
  // Warn about missing required columns
  if (missingRequired.length > 0) {
    errors.push(`Missing required columns for ${tableName}: ${missingRequired.join(', ')}`)
  }

  return {
    isValid: errors.length === 0,
    errors,
  }
}

/**
 * STRICT development-time guard: Validate payload before insert
 * 
 * This function prevents schema drift by:
 * - Rejecting any columns not in the schema contract
 * - Logging clear errors with exact mismatches
 * - Returning false to trigger safe fallback
 * 
 * CRITICAL: This guard MUST pass for all inserts to prevent database errors
 * and ensure code matches Supabase schema exactly.
 * 
 * @param {Object} payload - The data payload to validate
 * @param {string[]} allowedColumns - Array of allowed column names from schema contract
 * @param {string} tableName - Name of the table
 * @returns {boolean} - True if payload is valid and matches schema exactly, false otherwise
 */
export function guardPayload(payload, allowedColumns, tableName) {
  const validation = validatePayload(payload, allowedColumns, tableName)
  
  if (!validation.isValid) {
    // STRICT: Log clear error with full context
    console.error(`🚨 SCHEMA VALIDATION FAILED for ${tableName}:`)
    validation.errors.forEach(error => console.error(`   ${error}`))
    console.error(`   Payload received:`, payload)
    console.error(`   Payload keys: [${Object.keys(payload).join(', ')}]`)
    console.error(`   Schema allows: [${allowedColumns.join(', ')}]`)
    console.error(`   ❌ Database write SKIPPED - falling back to in-memory mode`)
    console.error(`   🔧 ACTION REQUIRED: Fix payload to match schema contract in supabaseSchema.js`)
    
    return false
  }
  
  return true
}

